
#define PHASE_FLOW   [3]
#define PHASE_ARRAY  [2]
#define PHASE_STREAM [1]
#define PHASE_INNER  [0]

#define INLINE_FLOW   INLINE PHASE_FLOW
#define INLINE_ARRAY  INLINE PHASE_ARRAY
#define INLINE_STREAM INLINE PHASE_STREAM
#define INLINE_INNER  INLINE PHASE_INNER
